{% set name = "apache-airflow-providers-mysql" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 61c9eb2f92f082125c67fa2c272ee2317216aece05d72ab6f1b7b07b67dcfd5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - apache-airflow >=2.0.0
    - mysql-connector-python >=8.0.11,<=8.0.22
    - mysqlclient >=1.3.6,<1.4
    - python >=3.6

test:
  imports:
    - airflow.providers.mysql
    - airflow.providers.mysql.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for MySQL for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
