{% set name = "apache-airflow-providers-mysql" %}
{% set version = "2.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 4f22a47368a8a9c0b861082bcaeacf297ed9d825eb972dcb4b8e8719df5c86ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - mysql-connector-python >=8.0.11
    - mysqlclient >=1.3.6

test:
  imports:
    - airflow.providers.mysql
    - airflow.providers.mysql.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for MySQL for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
