{% set name = "apache-airflow-providers-mysql" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 806018ad3264e210c61236593f4a9f821b743832906eda01717a54d4a2cbe850

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - mysql-connector-python >=8.0.11,<=8.0.22
    - mysqlclient >=1.3.6,<3

test:
  imports:
    - airflow.providers.mysql
    - airflow.providers.mysql.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for MySQL for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
