{% set name = "apache-airflow-providers-mysql" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-mysql-{{ version }}.tar.gz
  sha256: d34b60c8f7fdfd0e57d53c14ef4a40f1fc8215868cde852cd29e8300fdbb5b05

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - apache-airflow >=2.2.0
    - mysql-connector-python >=8.0.11
    - mysqlclient >=1.3.6
    - python

test:
  imports:
    - airflow.providers.mysql
    - airflow.providers.mysql.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-mysql package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
